name: build-name-dot-com-webhook
on:
  create:
    tags:
      - ^v\d{1,}\.\d{1,}\.\d{1,}$

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      DOCKER_REGISTRY: ghcr.io/wouldgo
      DOCKER_IMAGE: name-dot-com-webhook
      DOCKER_TARGET_PLATFORM: linux/arm64
    steps:
      -
        id: checkout
        name: Checkout the code
        uses: actions/checkout@v2
      -
        id: install-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      -
        id: prepare
        name: Prepare
        run: |
          echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
          echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}
          echo ::set-output name=version::$(git describe | sed -e 's/v//g')
      -
        id: login-registry
        name: Log into registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} \
            --password-stdin
      -
        id: build
        name: Build
        run: |
          docker build \
          --platform ${{ steps.prepare.outputs.docker_platform }} \
          --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} \
          --push \
          .
